---
# Install Database service

- name: check MySQL install
  shell: docker ps -a | grep -q openstack-mysql
  register: result
  ignore_errors: True

- name: install MySQL
  shell: docker run --net=host --name openstack-mysql -e MYSQL_ROOT_PASSWORD={{ database_root_password }} -d mysql:latest
  when: result|failed

- name: wait MySQL start
  shell: sleep 5
  when: result|failed
