---
# Install Database service

- name: install MySQL client
  apt: name=mysql-client

- name: check MySQL install
  shell: docker ps -a | grep -q openstack-mysql
  register: result
  ignore_errors: True

- name: install MySQL if not
  shell: docker run --net=host --name openstack-mysql -e MYSQL_ROOT_PASSWORD={{ database_root_password }} -d mysql:latest
  when: result|failed

- name: check keystone database
  shell: mysql -h 127.0.0.1 -uroot -p{{ database_root_password }} -N -s -e "show databases;" | grep -q keystone
  register: result
  ignore_errors: True

- name: create initial keystone database
  template: src=init_keystone.sql.j2 dest=/tmp/init_keystone.sql
  when: result|failed

- name: install initial keystone database
  shell: mysql -h 127.0.0.1 -uroot -p{{ database_root_password }} -N -s -e "source /tmp/init_keystone.sql;"
  when: result|failed
