---
# Nodes task

- name: install python-mysqldb
  apt: name=python-mysqldb

- name: install wget
  apt: name=wget

- name: install crudini
  shell: |
    mkdir .build_pip
    (cd .build_pip && wget -q https://bootstrap.pypa.io/get-pip.py && python get-pip.py && cd ..)
    pip install crudini
  args:
    creates: /usr/local/bin/crudini
