---
# Install Docker

- name: install docker
  apt: name=docker.io

- name: join a user in the docker group
  command: addgroup vagrant docker

- name: make Common Dockerfile directory
  shell: mkdir -p {{ dockerfile_install_dir }}/common

- name: install Common Dockerfile
  copy: src=Dockerfile dest={{ dockerfile_install_dir }}/common/Dockerfile

- name: install monit_openssh-server.conf
  copy: src=monit_openssh-server.conf dest={{ dockerfile_install_dir }}/common/monit_openssh-server.conf

- name: install maintenance ssh config
  copy: src=sshd_config dest={{ dockerfile_install_dir }}/common/sshd_config

- name: install set maintenance port script
  copy: src=set_maintenance_port.sh dest={{ dockerfile_install_dir }}/common/set_maintenance_port.sh

- name: create maintenance ssh key
  shell: echo -e 'n\n' | ssh-keygen -q -t rsa -P '' -f {{ dockerfile_install_dir }}/common/maintenance_id_rsa
  ignore_errors: True

- name: build Common Dockerfile
  shell: docker build -t {{ common_docker_image }} . > docker_build.log 2>&1
  args:
    chdir: "{{ dockerfile_install_dir }}/common"

- name: install nsenter
  shell: docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter
  args:
    creates: /usr/local/bin/nsenter

- name: install nsenter convenient script
  shell: |
    export nse={{ dockerfile_install_dir }}/common/nse.sh
    echo '#!/bin/bash' > ${nse}
    echo 'set -eux' >> ${nse}
    echo 'nsenter --mount --uts --ipc --net --pid --target $1' >> ${nse}
    chmod a+x ${nse}
  args:
    creates: "{{ dockerfile_install_dir }}/common/nse.sh"
